### ISSUE TITLE
SDWebServer

### ISSUE THREAD

**Issue by rel1ct** [bbx10/WebServer_tng#2]
Example SDWebServer. When I try to open in a browser index.htm the port monitor displays the message "Sent less data than expected!"
`dataFile:  1
dataType:  text/html
dataFile.size():  451
`

**Comment by bbx10** [comment]
Looks like the template streamFile does not work on ESP32.

**Comment by bbx10** [comment]
Workaround pushed https://github.com/bbx10/WebServer_tng/commit/8ad6d23dcf16f0fe598bf42bffbcb2638180e75a.

The index.htm and pins.png now appear in the browser.

**Comment by rel1ct** [comment]
Next problem.
 In file names "/"
`0	Object
type	"file"
name	"/index.htm"
1	Object
type	"dir"
name	"/edit"
2	Object
type	"file"
name	"/pins.png"`
In the folder name "//"
`Object
type	"file"
name	"//edit/index.htm"
1	Object
type	"file"
name	"//edit/ace.js"`
When you try to open files in the editor, the queries look like this:
`GET XHR http://index.htm/
GET XHR http://edit///edit/index.htm
`
Sorry for bad english.

**Comment by bbx10** [comment]
As far as I can tell, the example works the same on ESP8266 and ESP32. I am not sure what you are doing.

**Comment by rel1ct** [comment]
ESP8266 ("Generic ESP8266 Module" example SDWebServer):
open http//192.168.1.12/edit:
request to server: `http://192.168.1.12/list`
server response: `[{"type":"file","name":"INDEX.HTM"},{"type":"dir","name":"EDIT"},{"type":"file","name":"PINS.PNG"}]`
open folder "EDIT":
request to server: `http://192.168.1.12/list`
server response: `[{"type":"file","name":"INDEX.HTM"},{"type":"file","name":"ACE.JS"}]`
open file "INDEX.HTM" in folder "EDIT":
request to server: `http://192.168.1.12/edit/index.htm`
server response: `"<!DOCTYPE html><html>.....</html>"`
Example works correctly!

ESP32 ("ESP32 Dev Module" example SDWebServer):
open http//192.168.1.5/edit:
request to server: `http://192.168.1.5/list`
server response: `[{"type":"file","name":"/index.htm"},{"type":"dir","name":"/edit"},{"type":"file","name":"/pins.png"}]`
open folder "EDIT":
request to server: `http://192.168.1.5/list`
server response: `[{"type":"file","name":"//edit/index.htm"},{"type":"file","name":"//edit/ace.js"}]`
open file "INDEX.HTM" in folder "EDIT":
request to server: `http://edit///edit/index.htm`

Why in the second case the server(ESP32) gives the name of the file since "/" ?
The last request is just epic.

**Comment by chomik434** [comment]
rel1ct: Hi, have you found a solution?
