### ISSUE TITLE
SDWebServer.ino

### ISSUE THREAD

**Issue by rel1ct** [bbx10/WebServer_tng#3]
209   `output += entry.name();`   del
209   `output += String(entry.name()).substring(1);`   add

**Comment by bbx10** [comment]
Ok, I see now that the LIST command was returning file and directory names with a leading '/' prefix on ESP32 but not on ESP8266. Here is the final fix https://github.com/bbx10/WebServer_tng/commit/ac04e851838d926f611810effc74d22a1472e361
