### ISSUE TITLE
Download time

### ISSUE THREAD

**Issue by rel1ct** [bbx10/WebServer_tng#9]
### WebServer_tng
```
WebServer
update?

Update: upload_SPIFFS_esp32.ino.esp32.bin
Update Success: 530304 B
Download time: 59 sec.
Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:956
load:0x40078000,len:0
load:0x40078000,len:11904
entry 0x40078a3c

WebServer
update! 
```
### ESPAsyncWebServer
```
AsyncWebServer
update?

Update Start: sketch_nov04a.ino.esp32.bin
Update Success: 515152 B
Download time: 1 sec.
Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:956
load:0x40078000,len:0
load:0x40078000,len:11904
entry 0x40078a3c

AsyncWebServer
update!

```
difference of 58 seconds, is this normal !?

[WebServer.pcapng](https://cloud.mail.ru/public/7q4q/dLVUPe4Vc)
[AsyncWebServer.pcapng](https://cloud.mail.ru/public/CTJJ/24v7beBa9)

**Comment by allex1978** [comment]
Hi bbx10 thanks for you work. very usefull thing to port projects from esp8266. but upload speed extremely slow. 10 time slower than esp8266. another issue the pages with external css and js .... not load css and js. browser say "connection refused"  looks like when esp32 get new connection it drops previous client. i solved this via javascript. i load css and js one by one in a query but this is not best solution.
